
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 51
#define YY_END_OF_BUFFER 52
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[232] =
    {   0,
        0,    0,   52,   50,   49,   48,   39,   44,   27,   37,
       45,   30,   31,   25,   23,   17,   24,   40,   26,    7,
        7,   16,   15,   14,   20,   13,   10,   46,   46,   46,
       32,   33,   34,   47,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   28,   38,   29,
       18,    0,   43,   35,   21,   22,    6,    0,    1,    0,
        7,    0,    5,    7,    7,    9,   12,   19,   11,    8,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,    3,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,

       46,   46,   46,   46,   36,    0,    0,    1,    6,    7,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,    4,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,    2,   46,   41,    4,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,    4,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,    4,   42,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,    7,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,

       46,   46,   46,   46,   46,   46,   46,   46,   46,    7,
       46,    7,    7,   46,   46,   46,   46,   46,   46,   46,
        7,   46,   46,   46,   46,   46,   46,   46,   46,   46,
        0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   22,   24,   22,   25,   26,   27,
       28,   29,   30,    1,   31,   31,   31,   31,   31,   32,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   34,   33,   33,   33,   35,   33,   33,
       36,    1,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   33,   49,   50,   51,   52,
       53,   54,   33,   55,   56,   57,   58,   59,   60,   61,
       62,   33,   63,   64,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1,    1,    1,    1,
        5,    5,    6,    6,    7,    1,    1,    1,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    8,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        7,    6,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[241] =
    {   0,
        0,    0,  557,  558,  558,  558,  528,  550,  558,  547,
      558,  558,  558,  558,  541,  558,  538,   49,   63,   60,
       61,  558,  558,   53,  523,   54,  558,   67,  105,   37,
      558,  558,  558,  558,   57,   54,   56,   53,   90,  101,
       65,   61,   58,   74,   77,  102,  510,  558,  485,  558,
      558,  543,  558,  558,  558,  558,  137,  536,    0,  145,
      136,    0,  558,  122,  132,  558,  558,  558,  558,  558,
        0,  506,  132,   75,  133,  134,  135,  505,  136,  149,
       80,  143,  150,  155,  141,  158,  504,  159,  160,  161,
      164,  137,  163,  166,  171,  178,  165,  183,  169,  180,

      167,  185,  186,  187,  558,  532,  526,    0,  226,    0,
      195,  192,  191,  501,  212,  213,  214,  217,  219,  500,
      218,  223,  493,  492,  224,  225,  259,  227,  220,  228,
      221,  232,  241,  194,  246,  248,  250,  247,  253,  254,
      256,  558,  257,  491,  480,  260,  268,  262,  266,  271,
      272,  274,  277,  279,  281,  282,  481,  484,  481,    0,
      284,  285,  457,  325,  456,  283,  310,  286,  296,  291,
      312,  314,  313,  317,  344,  447,  328,  321,  329,  316,
      330,  351,  335,  295,  336,  382,  390,  337,  341,  345,
      338,  375,  346,  349,  376,  378,  461,  464,  458,  379,

      380,  381,  383,  382,  384,  431,  417,  356,  353,  391,
      436,  451,    0,  387,  388,  389,  424,  390,  395,  409,
        0,  421,  218,  114,  422,  437,  423,   75,  436,  438,
      558,  485,  491,  497,  502,  510,  518,  523,  526,  531
    } ;

static yyconst flex_int16_t yy_def[241] =
    {   0,
      231,    1,  231,  231,  231,  231,  231,  232,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  233,
      234,  231,  231,  231,  231,  231,  231,  235,  235,   29,
      231,  231,  231,  231,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,  231,  231,  231,
      231,  232,  231,  231,  231,  231,  231,  236,  237,  231,
      233,  238,  231,  239,  234,  231,  231,  231,  231,  231,
      240,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,

       29,   29,   29,   29,  231,  236,  231,  237,  231,  238,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,  231,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,  240,  240,  240,  240,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,  240,  240,   29,   29,   29,
       29,   29,   29,   29,   29,   29,  240,  240,  240,   29,

       29,   29,   29,   29,   29,  240,  240,   29,   29,  186,
      240,  187,  187,   29,   29,   29,   29,   29,   29,   29,
      211,   29,  240,  240,   29,   29,   29,  240,   29,   29,
        0,  231,  231,  231,  231,  231,  231,  231,  231,  231
    } ;

static yyconst flex_uint16_t yy_nxt[624] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       21,   21,   21,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   28,   30,   28,   31,   32,   33,   34,   28,
       35,   36,   37,   38,   39,   28,   28,   40,   28,   28,
       41,   28,   28,   42,   43,   44,   45,   46,   47,   28,
       28,   28,   48,   49,   50,   57,   57,   57,   57,   57,
       57,   57,   57,   58,   60,   60,   72,   64,   59,   66,
       67,   69,   70,   71,   71,   71,   71,   71,   71,   71,
       71,   74,   72,   77,   62,   72,   72,   96,  160,   80,

       92,   97,   81,   78,   90,   71,   79,   63,   63,   75,
       93,   76,   91,   72,   72,   94,   72,   98,   95,   72,
       62,   71,   71,   71,   71,   71,   71,   71,   71,   82,
       99,  101,  112,  100,  160,  121,   60,   83,  102,   84,
       72,   72,   85,   71,   73,   87,   60,   86,   64,  103,
       60,   88,   89,   57,   57,   57,   57,   57,   57,   57,
       57,  109,  109,  109,  109,  109,  109,  109,  109,   63,
      231,   72,   72,   72,   72,   72,   72,  114,  129,   63,
       72,  111,   72,   63,   63,  113,  118,  119,   72,   72,
      115,  116,  122,  120,   72,   87,  231,   72,   72,   72,

       72,  123,   72,   72,   72,   72,   72,  124,  137,  125,
       72,  133,  126,  131,   87,  128,  127,   72,  132,   72,
      130,  135,   72,  138,   72,   72,   72,  139,   87,  134,
       72,   72,  136,   72,   72,  144,  228,  141,  140,  168,
      145,   87,  109,  109,  109,  109,  109,  109,  109,  109,
      143,   72,   72,   72,  147,   87,   72,   72,   72,   72,
       72,   87,   72,   72,   72,   87,   72,   72,  163,  148,
      149,   72,  153,   63,  150,  151,  157,  156,  158,  165,
       72,  159,  160,  164,  162,   72,   72,   72,  166,   72,
      167,  170,   72,   72,  172,   72,   72,   87,   72,   72,

      176,   72,  161,  169,  173,   72,  171,   72,   87,  174,
       72,   72,  175,   72,   87,  177,   72,   87,   72,  178,
       72,   72,   72,   72,   72,   72,  189,   87,  181,   87,
       72,  179,  192,  180,   72,   72,  183,  182,  184,  208,
      164,  186,  187,  187,  187,  187,  187,  187,  187,   72,
      191,   72,   72,   72,  195,   72,   72,  190,  196,  193,
       72,  197,  204,  198,   72,  194,  199,   72,   72,   72,
      206,  201,  202,  207,   72,   72,   72,   72,  203,  205,
       72,  209,  215,   72,   72,   72,   87,   87,   72,   87,
       72,   87,   72,  214,  145,  220,   87,  200,  210,  210,

      210,  210,  210,  210,  210,  210,  212,  213,  213,  213,
      213,  213,  213,  213,   72,   72,  211,   72,   72,   72,
       72,   72,   72,   72,   87,   71,   72,   72,   72,   72,
       87,   87,   87,   87,   72,  216,  219,  160,  218,   87,
      217,  223,  211,  145,  222,   87,  224,  225,   72,  160,
      226,   71,  221,  221,  221,  221,  221,  221,  221,  221,
       72,   72,   72,   72,  227,   87,  221,  221,  212,  212,
      212,  212,  212,  212,  212,   72,   72,   72,  160,  229,
       87,  230,  160,  160,   87,   52,   72,   52,   52,   52,
       52,   52,   52,   61,   61,  188,  185,   61,   61,   65,

       65,  160,  160,  160,   65,   72,   72,   72,   72,   72,
      106,  106,  106,  106,  106,  106,  106,  106,  108,   72,
      108,  108,  108,  108,  108,  108,  110,  110,   64,   64,
       72,  155,  154,   64,   71,   71,   71,   71,   71,  152,
      146,  142,  107,   72,  117,   72,  107,   53,  105,  104,
       68,   56,   55,   54,   53,   51,  231,    3,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231
    } ;

static yyconst flex_int16_t yy_chk[624] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   18,   18,   18,   18,   18,
       18,   18,   18,   19,   20,   21,   30,   21,   19,   24,
       24,   26,   26,   28,   28,   28,   28,   28,   28,   28,
       28,   30,   38,   36,   20,   37,   35,   43,  228,   37,

       42,   43,   38,   36,   41,   28,   36,   20,   21,   35,
       42,   35,   41,   44,   74,   42,   45,   44,   42,   81,
       20,   29,   29,   29,   29,   29,   29,   29,   29,   39,
       44,   45,   74,   44,  224,   81,   64,   39,   45,   39,
       40,   46,   39,   29,   29,   40,   65,   39,   65,   46,
       61,   40,   40,   57,   57,   57,   57,   57,   57,   57,
       57,   60,   60,   60,   60,   60,   60,   60,   60,   64,
       61,   73,   75,   76,   77,   79,   92,   76,   92,   65,
       85,   73,   82,   61,   57,   75,   79,   79,   80,   83,
       77,   77,   82,   80,   84,   85,   61,   86,   88,   89,

       90,   83,   93,   91,   97,   94,  101,   84,   99,   86,
       95,   95,   88,   94,   90,   91,   89,   96,   94,  100,
       93,   97,   98,   99,  102,  103,  104,  100,  101,   96,
      113,  112,   98,  134,  111,  112,  223,  103,  102,  134,
      113,  104,  109,  109,  109,  109,  109,  109,  109,  109,
      111,  115,  116,  117,  116,  115,  118,  121,  119,  129,
      131,  121,  122,  125,  126,  125,  128,  130,  129,  117,
      118,  132,  122,  109,  119,  119,  127,  126,  127,  131,
      133,  127,  127,  130,  128,  135,  138,  136,  132,  137,
      133,  136,  139,  140,  138,  141,  143,  140,  127,  146,

      143,  148,  127,  135,  138,  149,  137,  147,  146,  139,
      150,  151,  141,  152,  147,  149,  153,  148,  154,  151,
      155,  156,  166,  161,  162,  168,  166,  150,  154,  168,
      170,  152,  170,  153,  184,  169,  156,  155,  161,  184,
      162,  164,  164,  164,  164,  164,  164,  164,  164,  167,
      169,  171,  173,  172,  173,  180,  174,  167,  174,  171,
      178,  175,  180,  175,  164,  172,  175,  177,  179,  181,
      182,  177,  178,  182,  183,  185,  188,  191,  179,  181,
      189,  185,  189,  175,  190,  193,  190,  193,  194,  191,
      182,  183,  209,  188,  194,  208,  209,  175,  186,  186,

      186,  186,  186,  186,  186,  186,  187,  187,  187,  187,
      187,  187,  187,  187,  192,  195,  186,  196,  200,  201,
      202,  204,  203,  205,  196,  210,  214,  215,  216,  218,
      214,  192,  195,  218,  219,  200,  204,  207,  202,  203,
      201,  217,  186,  216,  215,  205,  217,  219,  220,  206,
      220,  210,  211,  211,  211,  211,  211,  211,  211,  211,
      222,  225,  227,  217,  222,  227,  211,  211,  212,  212,
      212,  212,  212,  212,  212,  229,  226,  230,  199,  225,
      226,  229,  198,  197,  230,  232,  176,  232,  232,  232,
      232,  232,  232,  233,  233,  165,  163,  233,  233,  234,

      234,  159,  158,  157,  234,  235,  235,  235,  235,  235,
      236,  236,  236,  236,  236,  236,  236,  236,  237,  145,
      237,  237,  237,  237,  237,  237,  238,  238,  239,  239,
      144,  124,  123,  239,  240,  240,  240,  240,  240,  120,
      114,  107,  106,   87,   78,   72,   58,   52,   49,   47,
       25,   17,   15,   10,    8,    7,    3,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/lexer.l"
#line 2 "src/lexer.l"
#include <stdio.h>
#include <stdlib.h>
#include "y.tab.h"
void yyerror(char *);

char Identifier_Array[2000][100], Int_Const_Array[2000][20], Float_Const_Array[2000][20], String_Const_Array[2000][100], Complex_Const_Array[2000][20], Error_Array[2000][100];

int i;
int yylineno;

int OP_Assign, OP_Add, OP_Sub, OP_Mult, OP_Div, OP_Mod, OP_unary_add, OP_unary_sub, OP_unary_and, OP_unary_or, OP_unary_not, OP_Pow, OP_relational_and, OP_relational_or, OP_equality, OP_less, OP_greater, OP_less_less, OP_greater_greater, OP_not_equal, OP_greater_eq, OP_less_eq ; //operators. Ternary is yet to be included. How to differentiate unary add and binary add? 

int KEY_break, KEY_case, KEY_const, KEY_continue, KEY_default, KEY_else, KEY_fallthrough, KEY_for, KEY_func, KEY_if, KEY_import, KEY_interface, KEY_map, KEY_package, KEY_range, KEY_return, KEY_select, KEY_struct, KEY_switch, KEY_type, KEY_var, KEY_class, KEY_private, KEY_protected, KEY_public, KEY_static, KEY_try, KEY_catch, KEY_finally; //all keywords

int  L_Paran, R_Paran, L_Curly, R_Curly, L_SqBracket, R_SqBracket;

int  T_Int, T_Bool, T_String, T_Int8, T_Int16, T_Int32, T_Int64, T_Uint, T_Uint16, T_Uint32, T_Uint64, T_Uintptr,  T_Float32, T_Float64, T_Complex64, T_Complex128; //remember byte is an alias for U_Int8 and rune is an alias for int32

int Identifiers = 0;

int SemiColon, Comma, Question, Colon, UnderScore, Dots, DoubleQuotes, SingleQuotes;
int Line_No[2000];
int Int_Const, Float_Const, Complex_Const, String_Const, Bool_True, Bool_False;
int Error;
int Single_Line_Comment;
int Multiple_Line_Comment; //iske sath deal karna hai. Kab tak ignore karna hai
#line 709 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 88 "src/lexer.l"


#line 930 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 232 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 558 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 90 "src/lexer.l"
{Single_Line_Comment++; return Single_line_comment;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 91 "src/lexer.l"
{Multiple_Line_Comment++;return Multi_line_comment;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 92 "src/lexer.l"
{if ( strcmp(yytext,"break")==0){ KEY_break++; return Key_break;}
				else if (strcmp(yytext, "case")==0) {KEY_case++; return Key_case;}
				else if (strcmp(yytext,"const")==0) {KEY_const++; return Key_const;}
				else if (strcmp(yytext, "continue")==0) {KEY_continue++; return Key_continue;}
				else if (strcmp(yytext,"default")==0) {KEY_default++; return Key_default;}
				else if (strcmp(yytext,"else")==0) {KEY_else++; return Key_else;}
				else if (strcmp(yytext,"fallthrough")==0) {KEY_fallthrough++; return Key_fallthrough;}
				else if (strcmp(yytext,"for")==0) {KEY_for++; return Key_for;}
				else if (strcmp(yytext,"func")==0) {KEY_func++; return Key_func;}
				else if (strcmp(yytext,"if")==0) {KEY_if++; return Key_if;}
				else if (strcmp(yytext,"import")==0) {KEY_import++; return Key_import;}
				else if (strcmp(yytext,"interface")==0) {KEY_interface++; return Key_interface;}
				else if (strcmp(yytext,"map")==0) {KEY_map++; return Key_map;}
				else if (strcmp(yytext,"package")==0) {KEY_package++; return Key_package;}
				else if (strcmp(yytext,"range")==0) {KEY_range++; return Key_range;}
				else if (strcmp(yytext,"return")==0) {KEY_return++; return Key_return;}
				else if (strcmp(yytext,"select")==0) {KEY_select++; return Key_select;}
				else if (strcmp(yytext,"struct")==0) {KEY_struct++; return Key_struct;}
				else if (strcmp(yytext,"switch")==0) {KEY_switch++; return Key_switch;}
				else if (strcmp(yytext,"type")==0) {KEY_type++; return Key_type;}
				else if (strcmp(yytext,"var")==0) {KEY_var++; return Key_var;}
				else if (strcmp(yytext,"class")==0) {KEY_class++; return Key_class;}
				else if (strcmp(yytext,"private")==0) {KEY_private++; return Key_private;}
				else if (strcmp(yytext,"protected")==0) {KEY_protected++; return Key_protected;}
				else if (strcmp(yytext,"public")==0) {KEY_public++; return Key_public;}
				else if (strcmp(yytext,"static")==0) {KEY_static++; return Key_static;}
				else if (strcmp(yytext,"try")==0) {KEY_try++; return Key_try;}
				else if (strcmp(yytext,"catch")==0) {KEY_catch++; return Key_catch;}
				else if (strcmp(yytext,"finally")==0) {KEY_finally++; return Key_finally;}
			return Keyword;
			}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 123 "src/lexer.l"
{if(strcmp(yytext, "int")==0) {T_Int++;return T_int;} 
				else if (strcmp(yytext, "bool")==0) {T_Bool++; return T_bool;}
				else if (strcmp(yytext, "string")==0) {T_String++; return T_string;}
				else if (strcmp(yytext, "int8")==0 || strcmp(yytext, "byte")==0) {T_Int8++; return T_int8;}
				else if (strcmp(yytext, "int16")==0) {T_Int16++; return T_int16;}
				else if (strcmp(yytext, "int32")==0 || strcmp(yytext, "rune")==0) {T_Int32++; return T_int32;}
				else if (strcmp(yytext, "int64")==0) { T_Int64++; return T_int64;}
				else if (strcmp(yytext, "uint")==0) { T_Uint++; return T_uint;}
				else if (strcmp(yytext, "uint16")==0) { T_Uint16++; return T_uint16; }
				else if (strcmp(yytext, "uint32")==0) { T_Uint32++; return T_uint32; }
				else if (strcmp(yytext, "uint64")==0) { T_Uint64++; return T_uint64; }
				else if (strcmp(yytext, "uintptr")==0) { T_Uintptr++; return T_uintptr;}
				else if (strcmp(yytext, "float32")==0) { T_Float32++; return T_float32;}
				else if (strcmp(yytext, "float64")==0) { T_Float64++; return T_float64;}
				else if (strcmp(yytext, "complex64")==0) { T_Complex64++; return T_complex64; }
				else if (strcmp(yytext, "complex128")==0) { T_Complex128++; return T_complex128; }
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 140 "src/lexer.l"
{strcpy(Complex_Const_Array[Complex_Const++], yytext); return Imaginary_lit;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 141 "src/lexer.l"
{strcpy(Float_Const_Array[Float_Const++], yytext); return Float_lit;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 142 "src/lexer.l"
{strcpy(Int_Const_Array[Int_Const++],yytext); return Int_lit;} 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 143 "src/lexer.l"
{OP_greater_greater++; return Op_greater_greater;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 144 "src/lexer.l"
{OP_less_less++; return Op_less_less;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 145 "src/lexer.l"
{Question++; return M_question;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 146 "src/lexer.l"
{OP_greater_eq++; return Op_greater_eq;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 147 "src/lexer.l"
{OP_less_eq++; return Op_less_eq;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 148 "src/lexer.l"
{OP_greater++; return Op_greater;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 149 "src/lexer.l"
{OP_less++; return Op_less;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 150 "src/lexer.l"
{SemiColon++; return M_semicolon;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 151 "src/lexer.l"
{Colon++; return M_colon;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 152 "src/lexer.l"
{Comma++; return M_comma;} 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 153 "src/lexer.l"
{OP_not_equal++; return Op_not_equal;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 154 "src/lexer.l"
{OP_equality++; return Op_equality;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 155 "src/lexer.l"
{OP_Assign++; return Op_assign;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 156 "src/lexer.l"
{OP_unary_add++; return Op_unary_add;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 157 "src/lexer.l"
{OP_unary_sub++; return Op_unary_sub;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 158 "src/lexer.l"
{OP_Add++; return Op_add;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 159 "src/lexer.l"
{OP_Sub++; return Op_sub;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 160 "src/lexer.l"
{OP_Mult++; return Op_mult;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 161 "src/lexer.l"
{OP_Div++; return Op_divide;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 162 "src/lexer.l"
{OP_Mod++; return Op_mod;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 163 "src/lexer.l"
{L_Curly++; return M_lcurly;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 164 "src/lexer.l"
{R_Curly++; return M_rcurly;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 165 "src/lexer.l"
{L_Paran++; return M_lparan;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 166 "src/lexer.l"
{R_Paran++; return M_rparan;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 167 "src/lexer.l"
{L_SqBracket++; return M_lsqbracket;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 168 "src/lexer.l"
{R_SqBracket++; return M_rsqbracket;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 169 "src/lexer.l"
{OP_Pow++; return Op_pow;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 170 "src/lexer.l"
{OP_relational_and++; return Op_relational_and;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 171 "src/lexer.l"
{OP_relational_or++; return Op_relational_or;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 172 "src/lexer.l"
{OP_unary_and++; return Op_unary_and;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 173 "src/lexer.l"
{OP_unary_or++; return Op_unary_or;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 174 "src/lexer.l"
{OP_unary_not++; return Op_unary_not;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 175 "src/lexer.l"
{Dots++; return M_dot;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 176 "src/lexer.l"
{Bool_True++; return Bool_true;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 177 "src/lexer.l"
{Bool_False++; return Bool_false;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 178 "src/lexer.l"
{strcpy(String_Const_Array[String_Const++], yytext); return String_lit;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 179 "src/lexer.l"
{DoubleQuotes++; return M_doublequotes;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 180 "src/lexer.l"
{SingleQuotes++; return M_singlequotes;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 181 "src/lexer.l"
{strcpy(Identifier_Array[Identifiers++],yytext); return Identifier;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 182 "src/lexer.l"
{UnderScore++; return M_underscore;}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 183 "src/lexer.l"
{yylineno++; }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 184 "src/lexer.l"
{; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 185 "src/lexer.l"
{Line_No[Error]=yylineno;strcpy(Error_Array[Error++],yytext); yyerror(Error_Array[Error-1]);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 186 "src/lexer.l"
ECHO;
	YY_BREAK
#line 1291 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 232 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 232 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 231);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 186 "src/lexer.l"


int yywrap(void) {
return 1;
}
/*int main(int argc, char* argv[]){
	FILE *fh;
	if (argc == 2 && (fh = fopen(argv[1], "r")))
        yyin = fh;
    else{
    	printf("File not given or unable to open\n");
    	return 1;
    }
	yylex();
	printf("\nToken\t  Occureneces\tLexemes\n");
	printf("_______________________________________\n\n");
	if(KEY_break > 0)printf("KEY_break\t%d\tbreak\n",KEY_break);
	if(KEY_case > 0)printf("KEY_case\t%d\tcase\n",KEY_case);
	if(KEY_const > 0)printf("KEY_const\t%d\tconst\n",KEY_const);
	if(KEY_continue > 0)printf("KEY_continue\t%d\tcontinue\n",KEY_continue);
	if(KEY_default > 0)printf("KEY_default\t%d\tdefault\n",KEY_default);
	if(KEY_else > 0)printf("KEY_else\t%d\telse\n",KEY_else);
	if(KEY_fallthrough > 0)printf("KEY_fallthrough\t%d\tfallthrough\n",KEY_fallthrough);
	if(KEY_for > 0)printf("KEY_for\t\t%d\tfor\n",KEY_for);
	if(KEY_func > 0)printf("KEY_func\t%d\tfunc\n",KEY_func);
	if(KEY_if > 0)printf("KEY_if\t\t%d\tif\n",KEY_if);
	if(KEY_import > 0)printf("KEY_import\t%d\timport\n",KEY_import);
	if(KEY_interface > 0)printf("KEY_interface\t%d\tinterface\n",KEY_interface);
	if(KEY_map > 0)printf("KEY_map\t\t%d\tmap\n",KEY_map);
	if(KEY_package > 0)printf("KEY_package\t%d\tpackage\n",KEY_package);
	if(KEY_range > 0)printf("KEY_range\t%d\trange\n",KEY_range);
	if(KEY_return > 0)printf("KEY_return\t%d\treturn\n",KEY_return);
	if(KEY_select > 0)printf("KEY_select\t%d\tselect\n",KEY_select);
	if(KEY_struct > 0)printf("KEY_struct\t%d\tstruct\n",KEY_struct);
	if(KEY_switch > 0)printf("KEY_switch\t%d\tswitch\n",KEY_switch);
	if(KEY_type > 0)printf("KEY_type\t%d\ttype\n",KEY_type);
	if(KEY_var > 0)printf("KEY_var\t\t%d\tvar\n",KEY_var);
	if(KEY_class > 0)printf("KEY_class\t%d\tclass\n",KEY_class);
	if(KEY_private > 0)printf("KEY_private\t%d\tprivate\n",KEY_private);
	if(KEY_protected > 0)printf("KEY_protected\t%d\tprotected\n",KEY_protected);
	if(KEY_public > 0)printf("KEY_public\t%d\tpublic\n",KEY_public);
	if(KEY_static > 0)printf("KEY_static\t%d\tstatic\n",KEY_static);
	if(KEY_try > 0)printf("KEY_try\t\t%d\ttry\n",KEY_try);
	if(KEY_catch > 0)printf("KEY_catch\t%d\tcatch\n",KEY_catch);
	if(KEY_finally > 0)printf("KEY_finally\t%d\tfinally\n",KEY_finally);
	
	
	if(T_Int > 0)printf("T_Int\t\t%d\tint\n",T_Int);
	if(T_Bool > 0)printf("T_Bool\t\t%d\tbool\n",T_Bool);
	if(T_String > 0)printf("T_String\t%d\tstring\n",T_String);
	if(T_Int8 > 0)printf("T_Int8\t\t%d\tint8\n",T_Int8);
	if(T_Int16 > 0)printf("T_Int16\t\t%d\tint16\n",T_Int16);
	if(T_Int32 > 0)printf("T_Int32\t\t%d\tint32\n",T_Int32);
	if(T_Int64 > 0)printf("T_Int64\t\t%d\tint64\n",T_Int64);
	if(T_Uint > 0)printf("T_Uint\t\t%d\tuint\n",T_Uint);
	if(T_Uint16 > 0)printf("T_Uint16\t%d\tuint16\n",T_Uint16);
	if(T_Uint32 > 0)printf("T_Uint32\t%d\tuint32\n",T_Uint32);
	if(T_Uint64 > 0)printf("T_Uint64\t%d\tuint64\n",T_Uint64);
	if(T_Uintptr > 0)printf("T_Uintptr\t%d\tuintptr\n",T_Uintptr);
	if(T_Float32 > 0)printf("T_Float32\t%d\tfloat32\n",T_Float32);
	if(T_Float64 > 0)printf("T_Float64\t%d\tfloat64\n",T_Float64);
	if(T_Complex64 > 0)printf("T_Complex64\t%d\tcomplex64\n",T_Complex64);
	if(T_Complex128 > 0)printf("T_Complex128\t%d\tcomplex128\n",T_Complex128);
	
	if(OP_Assign > 0){
		printf("OP_Assign\t%d\t=\n",OP_Assign);
	}
 	if(OP_Add > 0){
		printf("OP_Add\t\t%d\t+\n",OP_Add);
	}
	if(OP_Sub > 0){
		printf("OP_Sub\t\t%d\t-\n",OP_Sub);
	}
	if(OP_Mult > 0){
		printf("OP_Mult\t\t%d\t*\n",OP_Mult);
	}
	if(OP_Div > 0){
		printf("OP_Div\t\t%d\t/\n",OP_Div);
	}
	if(OP_Mod > 0){
		printf("OP_Mod\t\t%d\t%%\n",OP_Mod);
	}
	if(OP_unary_add > 0){
		printf("OP_unary_add\t%d\t++\n",OP_unary_add);  //unary add ka symbol
	}
	if(OP_unary_sub > 0){
		printf("OP_unary_sub\t%d\t--\n",OP_unary_sub); 	//unary sub ka symbol
	}
	if(OP_not_equal > 0){
		printf("OP_not_equal\t%d\t!=\n", OP_not_equal);
	}
	if(OP_unary_and > 0){
		printf("OP_unary_and\t%d\t&\n",OP_unary_and);
	}
	if(OP_unary_or > 0){
		printf("OP_unary_or\t%d\t|\n",OP_unary_or);
	}
	if(OP_unary_not > 0){
		printf("OP_unary_not\t%d\t!\n",OP_unary_not);
	}
	if(OP_Pow > 0){
		printf("OP_Pow\t\t%d\t^\n",OP_Pow);
	}
	if(OP_relational_and > 0){
		printf("OP_rel_and\t%d\t&&\n",OP_relational_and);	
	}
	if(OP_relational_or > 0){
		printf("OP_rel_or\t%d\t||\n",OP_relational_or);
	}
	if(OP_equality > 0){
		printf("OP_equality\t%d\t==\n",OP_equality);
	}
	if(OP_greater_greater > 0){
		printf("OP_gr_gr\t%d\t>>\n",OP_greater_greater);
	}
	if(OP_greater > 0){
		printf("OP_greater\t%d\t>\n",OP_greater);
	}
	if(OP_less_less > 0){
		printf("OP_less_less\t%d\t<<\n",OP_less_less);
	}
	if(OP_less > 0){
		printf("OP_less\t\t%d\t<\n",OP_less);
	}
	if(Identifiers > 0){
		printf("Identifier\t%d\t%s\n", Identifiers, Identifier_Array[0]);
		for( int i = 1; i < Identifiers; i++){
			printf(" \t \t \t%s\n", Identifier_Array[i]);
		}
	}
	
	if(L_Paran > 0){
		printf("L_Paran\t\t%d\t(\n",L_Paran);
	}
	if(R_Paran > 0){
		printf("R_Paran\t\t%d\t)\n",R_Paran);
	}
	if(L_Curly > 0){
		printf("L_Curly\t\t%d\t{\n",L_Curly);
	}
	if(R_Curly > 0){
		printf("R_Curly\t\t%d\t}\n",R_Curly);
	}
	if(L_SqBracket > 0){
		printf("L_SqBracket\t%d\t[\n",L_SqBracket);
	}
	if(R_SqBracket > 0){
		printf("R_SqBracket\t%d\t]\n",R_SqBracket);
	}
	
	if(SemiColon > 0){
		printf("SemiColon\t%d\t;\n",SemiColon);
	}
	if(Comma > 0){
		printf("Comma\t\t%d\t,\n",Comma);
	}
	if(Dots>0){
		printf("Dots\t\t%d\t.\n",Dots);
	}
	if(Question > 0){
		printf("Question\t\t%d\t?\n",Question);
	}
	if(Colon > 0){
		printf("Colon\t\t%d\t:\n",Colon);
	}
	if(UnderScore>0){
		printf("UnderScore\t%d\t_\n",UnderScore);
	}
	if(DoubleQuotes > 0){
		printf("DoubleQuotes\t%d\t\"\n",DoubleQuotes);
	}
	if(SingleQuotes > 0){
		printf("SingleQuotes\t%d\t\'\n",SingleQuotes);
	}
	if(Int_Const > 0){
		printf("Int_Const\t%d\t%s\n", Int_Const, Int_Const_Array[0]);
		for( int i = 1; i < Int_Const; i++){
			printf(" \t \t \t%s\n", Int_Const_Array[i]);
		}
	}
	if(Float_Const > 0){
		printf("Float_Const\t%d\t%s\n", Float_Const, Float_Const_Array[0]);
		for( int i = 1; i < Float_Const; i++){
			printf(" \t \t \t%s\n", Float_Const_Array[i]);
		}
	}
	if(Complex_Const > 0){
		printf("Complex_Const\t%d\t%s\n", Complex_Const, Complex_Const_Array[0]);
		for( int i = 1; i < Complex_Const; i++){
			printf(" \t \t \t%s\n", Complex_Const_Array[i]);
		}
	}
	if(String_Const > 0){
		printf("String_Const\t%d\t%s\n", String_Const, String_Const_Array[0]);
		for( int i = 1; i < String_Const; i++){
			printf(" \t \t \t%s\n", String_Const_Array[i]);
		}
	}
	
	if(Bool_True > 0){
		printf("Bool_True\t%d\tTrue\n",Bool_True);	
	}
	if(Bool_False > 0){
		printf("Bool_False\t%d\tFalse\n",Bool_False);
	}
	if(Error>0){
		printf("Total numbers of error: %d\n",Error);
		for(int i=0;i<Error;i++){
			printf("Unrecognized symbol %s in %d\n",Error_Array[i], Line_No[i]);
		}
		printf("\n");
	}
	
//	printf("%s\t%d\t%d\n", Identifier_Array[0], Bool_False, KEY_finally);
//	printf("%d\t%d\t%d\t\n", Bool_True, Bool_False, KEY_finally);
	fclose(fh);
	return 0;
}*/

